# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_auto_20170617_0237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(help_text='Full HTML allowed. Keep headers at h2 or smaller.'),
        ),
        migrations.AlterField(
            model_name='content',
            name='slug',
            field=models.SlugField(help_text='This is the url extension.', max_length=100, unique=True),
        ),
    ]
